# fly.toml app configuration file generated for random-chapter-picker on 2025-03-01T04:26:00+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'random-chapter-picker'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
